seu_lourival/android/app/build.gradle
seu_lourival/lib/main.dart
seu_lourival/pubspec.lock

Adiciona config de firebase ao projeto, atualiza pubspec e build grade.
---
---

feat: add firebase

---

seu_lourival/lib/_debug/page.dart
seu_lourival/lib/app/modules/login/page.dart
seu_lourival/lib/app/modules/sms_validation/controller.dart
seu_lourival/lib/app/modules/sms_validation/page.dart
seu_lourival/lib/core/utils/input_validators.dart
seu_lourival/lib/core/values/login_strings.dart
seu_lourival/lib/global_widgets/design_system/core/scaffold/scaffold.dart
seu_lourival/lib/global_widgets/design_system/field/text_field.dart

Adiciona validação de campo e máscara nas telas de login e sms.
---
---

feat: add validation and mask in login and sms fields

---

seu_lourival/lib/app/data/models/user_model.dart
seu_lourival/lib/app/modules/login/controller.dart
seu_lourival/lib/app/modules/login/page.dart
seu_lourival/lib/app/modules/users_manager/add_users_form/controller.dart
seu_lourival/lib/app/modules/users_manager/add_users_form/page.dart
seu_lourival/lib/core/utils/input_validators.dart
seu_lourival/lib/core/utils/string_formater_helper.dart
seu_lourival/lib/core/utils/string_regex.dart

- Permite cadastrar apenas usuários do tipo `morador`.
- Remove caracteres especiais do número de telefone ao cadastrar usuário no db de pré-registro
- Refatora model dos usuários ao adicionar e listar.
DB:
---
refactor: Uma alteração de código que não corrige um bug nem adiciona um recurso
---

refactor: add user model and types

---

seu_lourival/lib/app/modules/report/report_list/page.dart
seu_lourival/lib/app/modules/users_manager/add_users_form/page.dart
seu_lourival/lib/app/modules/users_manager/add_users_list/page.dart
seu_lourival/lib/app/modules/users_manager/registered_list/page.dart
seu_lourival/lib/app/widgets/custom_snack_bar.dart
seu_lourival/lib/core/values/colors.dart
seu_lourival/lib/global_widgets/design_system/core/scaffold/drawer/drawer.dart
seu_lourival/lib/global_widgets/design_system/core/scaffold/drawer/sidenav/sidenav.dart
seu_lourival/lib/global_widgets/design_system/field/text_field.dart

Cadastro de cores do tema.
---
style: Alterações que não afetam o significado do código (espaço em branco, formatação etc.)
---

style: color theme

---

seu_lourival/lib/app/data/models/report_model.dart
seu_lourival/lib/app/data/models/user_model.dart
seu_lourival/lib/app/modules/report/new_report/controller.dart
seu_lourival/lib/app/modules/report/new_report/repository.dart
seu_lourival/lib/app/modules/report/report_detail/page.dart
seu_lourival/lib/app/modules/report/report_list/page.dart
seu_lourival/pubspec.yaml

New report and Report Details fixes
Added call and whatsapp features
---
---

Feat: New report and Report Details changes

---

seu_lourival/lib/app/modules/report/report_detail/controller.dart
seu_lourival/lib/app/modules/report/report_detail/page.dart
seu_lourival/lib/core/values/strings.dart
seu_lourival/linux/flutter/generated_plugin_registrant.cc
seu_lourival/linux/flutter/generated_plugins.cmake
seu_lourival/macos/Flutter/GeneratedPluginRegistrant.swift
seu_lourival/pubspec.lock
seu_lourival/windows/flutter/generated_plugin_registrant.cc
seu_lourival/windows/flutter/generated_plugins.cmake

Refactor Detalhe do report
- adiciona snackbar de sucesso e erro ao baixar imagem
- muda ícone do botão de comunicação
---
refactor: Uma alteração de código que não corrige um bug nem adiciona um recurso
---

refactor: show snackbar

---

seu_lourival/lib/app/modules/report/report_detail/page.dart
seu_lourival/pubspec.yaml

Add image loading and placeholder for report details
---
---

Feat: image loader placeholder

---

seu_lourival/lib/app/data/models/report_model.dart
seu_lourival/lib/app/data/services/report_service.dart
seu_lourival/lib/app/modules/report/report_detail/page.dart
seu_lourival/lib/app/modules/report/report_list/controller.dart

Fix report list icons, filter by datetime and report author's homedata layout
---
refactor: Uma alteração de código que não corrige um bug nem adiciona um recurso
---

Refactor: report list icons, filter by datetime and report author's homedata layout

---

seu_lourival/lib/app/data/models/user_model.dart
seu_lourival/lib/app/data/services/user_service.dart
seu_lourival/lib/global_widgets/design_system/core/scaffold/drawer/sidenav/sidenav.dart

- Add user type attribute as Enum instead of String
- Shows logged user's name on Drawer
- Shows USER MANAGEMENT drawer item if user is ADMIN type
---
---

Feat: User type conditions

---

seu_lourival/lib/app/data/models/user_model.dart
seu_lourival/lib/app/modules/maintenance/binding.dart
seu_lourival/lib/app/modules/maintenance/controller.dart
seu_lourival/lib/app/modules/maintenance/page.dart
seu_lourival/lib/app/modules/maintenance/repository.dart
seu_lourival/lib/global_widgets/design_system/core/scaffold/drawer/sidenav/sidenav.dart
seu_lourival/lib/routes/pages.dart
seu_lourival/lib/routes/routes.dart

Create maintenance module
---
---

Feat: Create maintenance module

---

seu_lourival/lib/app/data/models/maintenance_contact_model.dart
seu_lourival/lib/app/modules/maintenance/controller.dart
seu_lourival/lib/app/modules/maintenance/page.dart
seu_lourival/lib/app/modules/maintenance/repository.dart
seu_lourival/lib/app/modules/maintenance/widgets/maintenance_contact_list_tile.dart

Shows maintenance contact list and whatsapp/phone call feature
---
---

Feat: Maintenance Contact List

---

seu_lourival/lib/app/modules/report/report_detail/page.dart
seu_lourival/lib/core/utils/ds_extensions.dart
seu_lourival/lib/core/utils/input_validators.dart
seu_lourival/lib/global_widgets/design_system/core/scaffold/scaffold-widget/scaffold-widget.dart
seu_lourival/lib/global_widgets/design_system/core/scaffold/scaffold.dart

- add propriedade `actions` ao `DSScaffold`
- add DSStringExtensions
---
---

add DSStringExtensions and add actions to DSScaffold

---

seu_lourival/.gitignore
seu_lourival/lib/app/data/models/report_model.dart
seu_lourival/lib/app/modules/report/new_report/page.dart
seu_lourival/lib/app/modules/report/report_detail/controller.dart
seu_lourival/lib/app/modules/report/report_detail/page.dart
seu_lourival/lib/global_widgets/dialog/confirm_dialog.dart

- add update de status do report
TODO:
- add integração real com o banco de dados
- refresh na lista
---
---

Feat/report detail/update status

---

seu_lourival/lib/app/modules/report/new_report/controller.dart
seu_lourival/lib/app/modules/report/new_report/repository.dart

- Função de salvar novo report possui tratamento de erro e exibirá um snackbar caso aconteça algo inesperado
- Exibe o novo report na tela com o id, para que o mesmo possa ser deletado assim que for adicionado
---
---

Fix receive id on report creation

---

seu_lourival/lib/app/modules/billboard/binding.dart
seu_lourival/lib/app/modules/billboard/controller.dart
seu_lourival/lib/app/modules/billboard/page.dart
seu_lourival/lib/app/modules/billboard/repository.dart
seu_lourival/lib/app/modules/billboard/widgets/custom_story_view.dart
seu_lourival/lib/app/modules/maintenance/widgets/maintenance_contact_list_tile.dart
seu_lourival/lib/global_widgets/design_system/core/scaffold/drawer/sidenav/sidenav.dart
seu_lourival/lib/routes/pages.dart
seu_lourival/pubspec.yaml

Projeto inicial do billboard
Prototipo do layout dos stories listados por categorias (mock)
---
---

Feat: Billboard - Initial Project

---

seu_lourival/lib/app/modules/billboard/controller.dart
seu_lourival/lib/app/modules/billboard/new_billboard/controller.dart
seu_lourival/lib/app/modules/billboard/page.dart
seu_lourival/lib/app/modules/billboard/repository.dart
seu_lourival/lib/app/modules/billboard/widgets/custom_story_view.dart

Adiciona funcionalidade de deletar um comunicado
Essa operação pode ser feita apenas pelo admin, e ao ser concluída, a tela é recarregada com dados do backend novamente
---
---

Feat: delete billboard feature

---

seu_lourival/lib/app/modules/users_manager/add_users_form/controller.dart
seu_lourival/lib/app/modules/users_manager/add_users_list/controller.dart
seu_lourival/lib/app/modules/users_manager/registered_list/controller.dart
seu_lourival/lib/core/utils/ds_extensions.dart

Gerenciamento de usuários
Corrige:
- regex de validação de nome válido
- filtro de comparação por tipo de usuário
---
---

fix: isValidName and filter user by type

---

seu_lourival/lib/app/data/services/email_service.dart
seu_lourival/lib/app/modules/users_manager/add_users_form/controller.dart
seu_lourival/pubspec.yaml

Envio de email quando um usuário for pré registrado
Adicionado um loading no cadastro de usuário
Tratamento de erro: Caso algo falhe, é exibido uma snackbar na tela
---
---

Feat: email pre register user

---

seu_lourival/lib/app/modules/billboard/widgets/custom_story_view.dart

adiciona flag para verificar se o usuário logado é admin e exibe o botão de deletar
---
---

Fix: add isAdmin verification to show delete button

---

seu_lourival/lib/app/data/services/user_service.dart
seu_lourival/lib/app/modules/maintenance/controller.dart
seu_lourival/lib/app/modules/maintenance/page.dart
seu_lourival/lib/app/modules/maintenance/repository.dart
seu_lourival/lib/app/modules/maintenance/widgets/maintenance_contact_list_tile.dart
seu_lourival/lib/app/modules/report/report_detail/page.dart
seu_lourival/lib/app/modules/report/report_list/page.dart

Ajuste geral de bugs
- Bug no layout da lista de manifesto. Quando o titulo era muito grande, dava overflow. Textfield do titulo está fixo para no maximo 2 linhas
- exibe speed dial para apenas o admin entrar em contato por telefone e WhatsApp com o criador do manifesto
- Exibe botão de deletar contato de manutenção apenas para o admin
---
---

Fix: fix some layout and feature bugs

---

seu_lourival/lib/app/data/models/user_model.dart
seu_lourival/lib/app/modules/billboard/new_billboard/controller.dart
seu_lourival/lib/app/modules/billboard/page.dart
seu_lourival/lib/app/modules/login_error/page.dart
seu_lourival/lib/app/modules/maintenance/controller.dart
seu_lourival/lib/app/modules/maintenance/page.dart
seu_lourival/lib/app/modules/report/new_report/page.dart
seu_lourival/lib/app/modules/report/report_detail/page.dart
seu_lourival/lib/app/modules/sms_validation/controller.dart
seu_lourival/lib/app/modules/users_manager/add_users_form/controller.dart

Fix de alguns bugs para a ultima entrega
---
---

Fix: general bugs last delivery

---

seu_lourival/lib/app/data/models/user_model.dart
seu_lourival/lib/app/data/services/user_service.dart
seu_lourival/lib/global_widgets/design_system/core/scaffold/drawer/sidenav/sidenav.dart

Remove unecessary files: iOS, mcOs, Linux and Web folders
---
---

Fix: remove unecessary files

---

seu_lourival/pubspec.lock

Adiciona o APK para download da terceira etapa
---
---

add apk for last delivery
